### ISSUE TITLE
Not repsonding in Home App

### ISSUE THREAD

**Issue by henkhb** [oznu/docker-homebridge#146] opened 2018-11-09 21:59 UTC
The Home App is very unresponsive. I need to change rooms to get a connection.
Any solution for that?

**Comment by oznu** [comment] 2018-11-10 03:59
What do you mean by "change rooms", do you mean in the Home app or physically walking to another room in your house?

**Comment by oznu** [comment] 2018-11-10 04:02
Found your other post which clarifies things.

https://github.com/nfarina/homebridge/issues/2058

This is usually caused by a poorly coded plugin not responding with what HomeKit expects, so HomeKit just gives up on the entire bridge.

I'll close this one as it's really a duplicate of your other issue, and it's more appropriate for the Homebridge repo. You could also try asking in the Homebridge Slack group.

**Closed by oznu** 2018-11-10 04:02 UTC
